# Generated by Django 3.1.3 on 2020-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('tags', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.ManyToManyField(related_name='publications', to='comments.Comment')),
                ('tags', models.ManyToManyField(related_name='publications', to='tags.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
