# Generated by Django 2.2.14 on 2020-12-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
